---
- hosts: all
  user: remote
  gather_facts: false
  connection: local
#  roles:
#    - vmware
  tasks:
    - name: Create a VM
      vmware_guest:
        hostname: 192.168.100.128
        customization:
          hostname: testvm_9
        username: root
        password: Painatal1@
        validate_certs: no
        folder: /
        name: testvm_11
        guest_id: ubuntu64Guest
        state: poweredon
        cdrom:
          type: iso
          iso_path: "[datastore1] ubuntu-16.04.3-server-amd64.iso"
        disk:
        - size_gb: 10
          type: thin
          datastore: datastore1
        hardware:
          memory_mb: 1024
          num_cpus: 2
          num_cpu_cores_per_socket: 2
          scsi: paravirtual
        networks:
        - name: VM Network
        wait_for_ip_address: no
      delegate_to: localhost
      register: deploy
