---
- hosts: database
  become: true
  tasks:

  - include: roles/docker/tasks/mysql.yml
  tags: [ 'database' ]

- hosts: webserver
  become: true
  gather_facts: false

  tasks:
  - include: roles/docker/tasks/apache.yml
             roles/docker/tasks/demo_app.yml
  tags: [ 'webserver ']

- hosts: loadbalancer
  become: true
  gather_facts: false

  tasks:
  - include: roles/docker/tasks/nginx.yml
  tags: [ 'loadbalancer' ]



