---
- hosts: database
  become: true

  roles:
    - docker
  tags: [ 'datatabase' ]

- hosts: webserver
  become: true
  gather_facts: false

  roles:
    - docker
  tags: [ 'webserver' ]

- hosts: loadbalancer
  become: true
  gather_facts: false

  roles:
    - docker
  tags: [ 'loadbalancer' ]


