---
- hosts: database
  become: true
  tasks:

  roles:
    - mysql
  tags: [ 'database' ]

- hosts: webserver
  become: true
  gather_facts: false

  roles:
     - apache2
     - demo_app
  tags: [ 'webserver' ]

- hosts: loadbalancer
  become: true
  gather_facts: false

  roles:
    - nginx
  tags: [ 'loadbalancer' ]

