---
- hosts: database
  become: true

  roles:
    - { role: docker, tags: [ 'database' ] }

- hosts: webserver
  become: true
  gather_facts: false

  roles:
    - { role: docker, tags: [ 'webserver' ] }

- hosts: loadbalancer
  become: true
  gather_facts: false

  roles:
    - { role: docker, tags: [ 'loadbalancer' ] }


