---
- hosts: database
  become: true
  tasks:

  roles:
    - mysql

- hosts: webserver
  become: true
  gather_facts: false

  roles:
     - apache2
     - demo_app

- hosts: loadbalancer
  become: true
  gather_facts: false

  roles:
    - nginx


