---
- name: Installing packages on VMs
  vmware_vm_shell:
    hostname: "{{ vmware_hostname }}"
    username: "{{ vmware_root_user }}"
    password: "{{ vmware_root_pass }}"
    datacenter: ha-datacenter
    folder: /  
    validate_certs: no
    vm_id: "{{ vmware_vm_name[0] }}"
    vm_username: "{{ vm_user }}"
    vm_password: "{{ vm_user_pass }}" 
    vm_shell: /bin/echo
    vm_shell_args: " install {{ item }} "
    vm_shell_cwd: "/tmp"
  with_items:
    - "{{ packages }}"
