---
- name: Installing packages on VMs
  vmware_vm_shell:
    hostname: "{{ vmware_hostname }}"
    username: "{{ vmware_root_user }}"
    password: "{{ vmware_root_pass }}"
    datacenter: ha-datacenter
    folder: /  
    validate_certs: no
    vm_id: "{{ vmware_vm_name }}"
    vm_username: "{{ vm_user }}"
    vm_password: "{{ vm_user_pass }}" 
    vm_shell: /usr/bin/sudo
    vm_shell_args: " apt-get install {{ item }} -y"
    vm_shell_cwd: "/tmp"
    vm_shell_env:
      - "PATH=/bin:/usr/local/bin:/usr/sbin:/usr/bin"
  with_items:
    - "{{ packages }}"
