---
- name: Get VMs currently configured on VMware
  vmware_guest_facts: 
    hostname: "{{ vmware_hostname }}" 
    username: "{{ vmware_root_user }}"
    password: "{{ vmware_root_pass }}"
    datacenter: ha-datacenter
    name: "{{ item }}"
    validate_certs: no
  with_items: 
    - "{{ vmware_vm_name }}"
