---
- import_tasks: create_vm.yml
  tags: [ 'create_vm' ]
- import_tasks: remove_vm.yml
  tags: [ 'remove_vm' ]
- import_tasks: get_vms.yml
  tags: [ 'get_vms' ]
- import_tasks: start_vm.yml
  tags: [ 'start_vm' ]
