---
- pause:  
    prompt: "Type the name of the VM to remove"
  register: vm_name

- name: Stopping VMs
  vmware_guest:
    hostname: "{{ vmware_hostname }}"
    username: "{{ vmware_root_user }}"
    password: "{{ vmware_root_pass }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: poweredoff

- name: Removing VMs
  vmware_guest:
    hostname: "{{ vmware_hostname }}"
    username: "{{ vmware_root_user }}"
    password: "{{ vmware_root_pass }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: absent
