---
- name: Stopping VM: "{{ item }}"
  vmware_guest:
    hostname: "{{ vmware_hostname }}"
    username: "{{ vmware_root_user }}"
    password: "{{ vmware_root_pass }}"
    validate_certs: no
    name: "{{ item }}"
    state: poweredoff
  with_items:
    - "{{ vmware_vm_name }}"

- name: Removing VM: "{{ item }}"
  vmware_guest:
    hostname: "{{ vmware_hostname }}"
    username: "{{ vmware_root_user }}"
    password: "{{ vmware_root_pass }}"
    validate_certs: no
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ vmware_vm_name }}"
