---
- name: Creating users
  user:
    name: "{{ item.name }}"
    password: "{{ ubuntu_default_password }}"
    group: "{{ item.group }}"
    create_home: yes
    state: present
    update_password: on_create
  with_items: 
    - "{{ user_details }}"
